apiVersion: v1
kind: Service
metadata:
  name: question-frontend-service
  labels:
    app: albanian-quora-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: ealbanian-quora-frontend
